//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class OrderTBL
    {
        public int OrderItemId { get; set; }

        /*[Required(ErrorMessage = "Name is required.")]*/
        public string Name { get; set; }

      /*  [Required(ErrorMessage = "Address is required.")]*/
        public string Address { get; set; }

    /*    [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid email format.")]*/
        public string Email { get; set; }

        /*[RegularExpression(@"^[0-9]{10,15}$", ErrorMessage = "Invalid mobile number.")]*/
        public Nullable<long> MobileNo { get; set; }

        /*[Required(ErrorMessage = "Payment option is required.")]*/
        public string PaymentOption { get; set; }

        /*[RegularExpression(@"^[0-9]{16}$", ErrorMessage = "Invalid credit card number.")]*/
        public string CardNumber { get; set; }

        /*[Required(ErrorMessage = "Expiry date is required.")]*/
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
